packages:
  - 'account-lookup'
  - 'assets'
  - 'authz-viewer'
  - 'bluecheck'
  - 'coming-soon'
  - 'crossmint-frontend'
  - 'crossmint-mobile'
  - 'dapp-example'
  - 'dashboard'
  - 'deployed-contract-listings'
  - 'developer-portal'
  - 'explorer'
  - 'expo-demo'
  - 'faucet'
  - 'kaito-dashboard'
  - 'mainnet-stats'
  - 'quickstart-frontend'
  - 'reclaim-demo'
  - 'staking'
  - 'voucher-verify-demo'
  - 'xion.js'
  - 'packages/*'
